- name: Set host IP mapping to /etc/hosts file of all instances
  hosts: server_1:server_2
  tasks:
    - name: Import Variables for host IP mapping
      include_vars: variables.yml
    
    - name: Update hosts file for all the Hosts
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR HOSTS IP VARIABLES"
        block: |
          {{web_private_ip}} web
          {{app_private_ip}} app