- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import Variables for VPC Setup
      include_vars: variables.yml
    
    - name: Create Project VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpcout

    - name: Create a Public subnet 1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: project-pubsub1
      register: pubsub1_out

    - name: Create a Public subnet 2 in Zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: project-pubsub2
      register: pubsub2_out

    - name: Create a Public subnet 3 in Zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: project-pubsub3
      register: pubsub3_out
    
    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: project_igw
      register: igw_out

    - name: Create Route table for public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        tags:
          Name: project_pubRT
      register: pubRT_out

    - name: Store VPC register output as a variables
      blockinfile:
        path: vars/variables.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR VPC SETUP VARIABLES"
        block: |
          vpcid: {{vpcout.vpc.id}}
          pubsub1id: {{pubsub1_out.subnet.id}}
          pubsub2id: {{pubsub2_out.subnet.id}}
          pubsub3id: {{pubsub3_out.subnet.id}}
          igwid: {{igw_out.gateway_id}}
          pubRTid: {{pubRT_out.route_table.id}}